import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { AutomationConfigFactory } from "../../packages/application/journey/src/config/automation-config.js";
import {
	type ActionManifest,
	automationActionPrefix,
	type Job,
	localWorkflowActionsRef,
	readWorkflow,
	readYaml,
	root,
	type Step,
	sortedKeys,
	type Workflow,
	workflowExpression,
} from "./support.js";

const publicWorkflowContracts = {
	"check-active-meetup-issues": {
		inputs: [
			"github-app-client-id",
			"google-drive-meetup-folder-id",
			"google-drive-meetup-template-folder-id",
			"kutt-link-id",
			"slack-channel-id",
		],
		outputs: ["issue-numbers"],
		secrets: [
			"github-app-private-key",
			"google-credentials",
			"kutt-api-key",
			"openfeedback-api-key",
			"slack-token",
		],
	},
	"update-meetup-issue": {
		inputs: [
			"github-app-client-id",
			"google-drive-meetup-folder-id",
			"google-drive-meetup-template-folder-id",
			"kutt-link-id",
			"slack-channel-id",
		],
		outputs: ["communication-diagnostics", "diagnostics", "is-ready", "state"],
		secrets: [
			"github-app-private-key",
			"google-credentials",
			"kutt-api-key",
			"openfeedback-api-key",
			"slack-token",
		],
	},
	"update-meetup-issue-form": {
		inputs: ["github-app-client-id"],
		outputs: [
			"changed",
			"changed-files",
			"diagnostics",
			"host-count",
			"is-valid",
			"referential-diagnostics",
			"speaker-count",
		],
		secrets: ["github-app-private-key"],
	},
	"check-meetup-referentials-and-issue-form": {
		inputs: [],
		outputs: [
			"host-count",
			"is-valid",
			"issue-form-changed",
			"issue-form-changed-files",
			"issue-form-diagnostics",
			"referential-diagnostics",
			"speaker-count",
		],
		secrets: [],
	},
} as const;

const expectedActionWiring = {
	"check-active-meetup-issues": {
		audit: [
			"publication/reconcile-feedback",
			"publication/reconcile-assets",
			"event/reconcile",
			"communication/reconcile",
		],
		list: ["event/list-active"],
	},
	"update-meetup-issue": {
		manage: [
			"communication/reconcile",
			"publication/reconcile-feedback",
			"publication/reconcile-assets",
			"event/reconcile",
		],
	},
	"update-meetup-issue-form": {
		synchronize: ["referential/validate", "referential/sync-issue-form"],
	},
	"check-meetup-referentials-and-issue-form": {
		validate: ["referential/validate", "referential/sync-issue-form"],
	},
} as const;

describe("public reusable workflow contracts", () => {
	it.each(Object.entries(publicWorkflowContracts))(
		"publishes the exact caller contract and generated documentation for %s",
		async (name, expected) => {
			// Arrange
			const workflow = await readWorkflow(name);
			const contract = workflow.on?.workflow_call;
			const documentation = await readFile(
				join(root, `.github/workflows/${name}.md`),
				"utf8",
			);

			// Act
			const actual = sortedKeys(contract?.inputs);
			const actual1 = sortedKeys(contract?.secrets);
			const actual2 = sortedKeys(contract?.outputs);

			// Assert
			expect(workflow.permissions).toEqual({});
			expect(actual).toEqual([...expected.inputs, "locale"].sort());
			expect(actual1).toEqual([...expected.secrets].sort());
			for (const secretName of expected.secrets) {
				expect(contract?.secrets?.[secretName]?.required).toBe(true);
			}
			expect(actual2).toEqual([...expected.outputs].sort());
			expect(documentation).toContain(
				`GitHub Reusable Workflow: ${workflow.name}`,
			);
			expect(documentation).toContain(
				"This documentation was automatically generated by [CI Dokumentor]",
			);
		},
	);

	it("creates every public workflow installation token from a required client ID", async () => {
		// Arrange
		const workflowFiles = (
			await readdir(join(root, ".github/workflows"))
		).filter((name) => name.endsWith(".yml") && !name.startsWith("__"));

		// Act
		const workflows = await Promise.all(
			workflowFiles.map(async (file) => {
				const workflow = await readYaml<Workflow>(`.github/workflows/${file}`);
				const tokens = Object.values(workflow.jobs ?? {})
					.flatMap((job) => job.steps ?? [])
					.filter((step) =>
						step.uses?.startsWith("actions/create-github-app-token@"),
					);
				return { file, contract: workflow.on?.workflow_call, tokens };
			}),
		);
		const tokenWorkflows = workflows.filter(({ tokens }) => tokens.length > 0);

		// Assert
		expect(tokenWorkflows.map(({ file }) => file).sort()).toEqual([
			"check-active-meetup-issues.yml",
			"update-meetup-issue-form.yml",
			"update-meetup-issue.yml",
		]);
		for (const { file, contract, tokens } of tokenWorkflows) {
			expect(contract?.inputs?.["github-app-client-id"], file).toMatchObject({
				required: true,
				type: "string",
			});
			expect(contract?.inputs, file).not.toHaveProperty("github-app-id");
			for (const token of tokens) {
				expect(token.with?.["client-id"], `${file}/${token.id}`).toBe(
					workflowExpression("inputs.github-app-client-id"),
				);
				expect(token.with, `${file}/${token.id}`).not.toHaveProperty("app-id");
			}
		}
	});

	it.each(["check-active-meetup-issues", "update-meetup-issue"])(
		"requires Slack credentials and forwards communication tokens and routing in %s",
		async (workflowName) => {
			// Arrange
			const communicationAction = `${automationActionPrefix}communication/reconcile`;

			// Act
			const workflow = await readWorkflow(workflowName);
			const secrets = workflow.on?.workflow_call?.secrets;
			const slackChannel =
				workflow.on?.workflow_call?.inputs?.["slack-channel-id"];
			const communicationSteps = Object.values(workflow.jobs ?? {})
				.flatMap((job) => job.steps ?? [])
				.filter((step) => step.uses === communicationAction);

			// Assert
			expect(secrets).not.toHaveProperty("mailings-token");
			expect(secrets?.["slack-token"]?.required).toBe(true);
			expect(slackChannel?.required).toBe(true);
			expect(slackChannel?.default).toBeUndefined();
			expect(communicationSteps).toHaveLength(1);
			expect(communicationSteps[0].with).toMatchObject({
				"mailings-token": workflowExpression(
					"steps.mailings-token.outputs.token",
				),
				"slack-token": workflowExpression("secrets.slack-token"),
				"slack-channel-id": workflowExpression("inputs.slack-channel-id"),
			});
			expect(communicationSteps[0].env).toBeUndefined();
		},
	);

	it.each([
		["check-active-meetup-issues", "audit"],
		["update-meetup-issue", "manage"],
	] as const)(
		"creates a revocable mailings-only token in the dispatch job in %s",
		async (workflowName, jobName) => {
			// Arrange
			const repositoryOwner = "example-community";
			const config =
				AutomationConfigFactory.createAutomationConfig(repositoryOwner);
			const communicationAction = `${automationActionPrefix}communication/reconcile`;

			// Act
			const workflow = await readWorkflow(workflowName);
			const jobs = Object.values(workflow.jobs ?? {});
			const steps = workflow.jobs?.[jobName]?.steps ?? [];
			const tokens = jobs
				.flatMap((job) => job.steps ?? [])
				.filter((step) => step.id === "mailings-token");
			const token = tokens[0];
			const tokenIndex = steps.indexOf(token);
			const communicationIndex = steps.findIndex(
				(step) => step.uses === communicationAction,
			);
			const jobOutputs = jobs.map((job) =>
				"outputs" in job ? job.outputs : {},
			);
			const publicOutputs = JSON.stringify([
				workflow.on?.workflow_call?.outputs,
				...jobOutputs,
			]);

			// Assert
			expect(tokens).toHaveLength(1);
			expect(token.uses).toMatch(
				/^actions\/create-github-app-token@[0-9a-f]{40}$/,
			);
			expect(token.if).toBeUndefined();
			expect(token.with).toEqual({
				"client-id": workflowExpression("inputs.github-app-client-id"),
				"private-key": workflowExpression("secrets.github-app-private-key"),
				owner: workflowExpression("github.repository_owner"),
				repositories: "mailings",
				"permission-contents": "write",
			});
			expect(`${repositoryOwner}/${token.with?.repositories}`).toBe(
				config.communication["mailings-repository"],
			);
			expect(tokenIndex).toBeGreaterThanOrEqual(0);
			expect(communicationIndex).toBeGreaterThan(tokenIndex);
			expect(steps[communicationIndex].with?.["mailings-token"]).toBe(
				workflowExpression("steps.mailings-token.outputs.token"),
			);
			expect(publicOutputs).not.toContain("steps.mailings-token.outputs.token");
		},
	);

	it.each(Object.entries(expectedActionWiring))(
		"loads actions from the reusable workflow revision in %s",
		async (workflowName, jobs) => {
			// Arrange
			const expectedJobs = Object.entries(jobs);

			// Act
			const workflow = await readWorkflow(workflowName);
			const wiring = expectedJobs.map(([jobName, expectedActions]) => {
				const actionNames = expectedActions as readonly string[];
				const job = workflow.jobs?.[jobName];
				const actionSteps = (job?.steps ?? []).filter((step: Step) =>
					step.uses?.startsWith(automationActionPrefix),
				);
				const workflowSourceIndex = (job?.steps ?? []).findIndex(
					(step: Step) =>
						step.id === "local-workflow-actions" &&
						step.uses === localWorkflowActionsRef &&
						step.with?.["actions-path"] === "actions",
				);
				const firstActionIndex = (job?.steps ?? []).indexOf(actionSteps[0]);
				return {
					jobName,
					actionNames,
					job,
					actionSteps,
					workflowSourceIndex,
					firstActionIndex,
				};
			});

			// Assert
			for (const {
				jobName,
				actionNames,
				job,
				actionSteps,
				workflowSourceIndex,
				firstActionIndex,
			} of wiring) {
				expect(job, `${workflowName}/${jobName}`).toBeDefined();
				expect(actionSteps.map((step: Step) => step.uses)).toEqual(
					actionNames.map((action) => `${automationActionPrefix}${action}`),
				);
				expect(
					workflowSourceIndex,
					`${workflowName}/${jobName} local workflow actions loader`,
				).toBeGreaterThanOrEqual(0);
				expect(workflowSourceIndex).toBeLessThan(firstActionIndex);
			}
		},
	);

	it.each([
		["check-meetup-referentials-and-issue-form", "validate", "check", "false"],
		["update-meetup-issue-form", "synchronize", "fix", undefined],
	] as const)(
		"lets referential actions enforce the configured drift policy in %s",
		async (workflowName, jobName, mode, failOnDrift) => {
			// Arrange
			const workflow = await readWorkflow(workflowName);

			// Act
			const job = workflow.jobs?.[jobName];
			const actions = (job?.steps ?? []).filter((step) =>
				step.uses?.startsWith(`${automationActionPrefix}referential/`),
			);

			// Assert
			expect(job).not.toHaveProperty("continue-on-error");
			expect(actions).toHaveLength(2);
			for (const action of actions) {
				expect(action).not.toHaveProperty("continue-on-error");
				expect(action.if).toBeUndefined();
			}
			expect(actions[1].with?.mode).toBe(mode);
			expect(actions[1].with?.["fail-on-drift"]).toBe(failOnDrift);
		},
	);

	it("pins every external workflow dependency to a full commit SHA", async () => {
		// Arrange
		const workflowFiles = (
			await readdir(join(root, ".github/workflows"))
		).filter((name) => name.endsWith(".yml"));
		const externalUses: string[] = [];

		// Act
		for (const file of workflowFiles) {
			const workflow = await readYaml<Workflow>(`.github/workflows/${file}`);
			for (const job of Object.values(workflow.jobs ?? {}) as Job[]) {
				if (job.uses && !job.uses.startsWith("./")) externalUses.push(job.uses);
				for (const step of job.steps ?? []) {
					if (step.uses && !step.uses.startsWith("./")) {
						externalUses.push(step.uses);
					}
				}
			}
		}
		for (const action of [
			"actions/publication/reconcile-assets",
			"actions/publication/reconcile-feedback",
			"actions/event/reconcile",
			"actions/event/list-active",
			"actions/referential/validate",
			"actions/referential/sync-issue-form",
			"actions/communication/reconcile",
		]) {
			const manifest = await readYaml<ActionManifest>(
				join(action, "action.yml"),
			);
			for (const step of manifest.runs?.steps ?? []) {
				if (step.uses && !step.uses.startsWith("./"))
					externalUses.push(step.uses);
			}
		}

		// Assert
		expect(externalUses.length).toBeGreaterThan(0);
		for (const uses of externalUses) {
			expect(uses).toMatch(/^[^@\s]+@[0-9a-f]{40}$/);
		}
	});
});
