name: "Meetup issue linter action"
description: "This action lint the meetup issue for required fields and format"
author: "Meetup DevOps Aix-Marseille"
branding:
  icon: check-circle
  color: blue

inputs:
  issue-number:
    description: "The issue number to lint."
    required: true
  issue-parsed-body:
    description: "The parsed issue body. See <https://github.com/issue-ops/parser>."
    required: true
  should-fix:
    description: "Whether to fix the issue or not."
    required: true
  github-token:
    description: "The GitHub token with permissions to update the issue."
    required: true

runs:
  using: node20
  main: dist/index.js
