name: "Meetup issue linter action"
description: "This action lint the meetup issue for required fields and format"
author: "Meetup DevOps Aix-Marseille"
branding:
  icon: check-circle
  color: blue

inputs:
  issue-number:
    description: "The issue number to lint."
    required: true
  issue-parsed-body:
    description: "The parsed issue body. See <https://github.com/issue-ops/parser>."
    required: true
  hosters:
    description: |
      JSON List of hosters to update. Example: ["Hoster 1", "Hoster 2"]
    required: true
  speakers:
    description: |
      JSON List of speakers to update. Example: ["Speaker One", "Speaker 2"]
    required: true
  should-fix:
    description: "Whether to fix the issue or not."
    required: false
    default: "true"
  fail-on-error:
    description: "Whether to fail on error or not."
    required: false
    default: "true"
  github-token:
    description: "The GitHub token with permissions to update the issue."
    required: true

outputs:
  lint-issues:
    description: "List of issues found in the meetup issue."

runs:
  using: node20
  main: dist/index.js
