name: "Meetup issue linter action"
description: "This action lint the meetup issue for required fields and format"
author: "Cloud Native Aix-Marseille"
branding:
  icon: check-circle
  color: blue

inputs:
  issue-number:
    description: "The issue number to lint."
    required: true
  issue-parsed-body:
    description: "The parsed issue body. See <https://github.com/issue-ops/parser>."
    required: true
  hosters:
    description: |
      JSON List of hosters to update.
      Example: `["Hoster 1", "Hoster 2"]`.
    required: true
  speakers:
    description: |
      JSON List of speakers with name and URL.
      Example: `[{"name": "Speaker One", "url": "https://example.com/speaker1"}, {"name": "Speaker Two", "url": "https://example.com/speaker2"}]`.
    required: true
  should-fix:
    description: "Whether to fix the issue or not."
    required: false
    default: "true"
  fail-on-error:
    description: "Whether to fail on error or not."
    required: false
    default: "true"
  github-token:
    description: "The GitHub token with permissions to update the issue."
    required: true
  google-credentials:
    description: "Google Drive service account credentials JSON for auto-creating drive folders."
    required: true
  google-parent-folder-id:
    description: "Google Drive parent folder ID where meetup folders will be created."
    required: true
  google-template-folder-id:
    description: "Google Drive template folder ID containing files to copy to new meetup folders."
    required: true

outputs:
  lint-issues:
    description: "List of issues found in the meetup issue."
  valid-meetup-issue:
    description: |
      Valid meetup issue data in JSON Object.
      Only valid data is outputted.

      - `number`: Issue number.
      - `title`: Issue title.
      - `parsed-body`: Parsed issue body.
      - `labels`: Issue labels.
      - `hoster`: Hoster data.
      - `speakers`: Speakers data.
      - `drive-files`:
        - `announcement-link`: Link to the announcement file in Google Drive.
        - `presentation-link`: Link to the presentation file in Google Drive.

runs:
  using: node20
  main: dist/index.js
