name: Internal - Main - Continuous Integration

on:
  push:
    branches: [main]
    tags: ["*"]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/__shared-ci.yml
    permissions:
      actions: read
      contents: read
      id-token: write
      issues: write
      packages: read
      pull-requests: write
      security-events: write
      statuses: write

  release:
    needs: ci
    uses: hoverkraft-tech/ci-github-publish/.github/workflows/release-actions.yml@a0a9d185c51c10710a5987822e78feb2b5ce1932 # 0.29.0
    permissions:
      contents: write
      pull-requests: write
    with:
      update-all: ${{ startsWith(github.ref, 'refs/tags/') }}
      github-app-client-id: ${{ vars.CI_BOT_APP_CLIENT_ID }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      github-app-key: ${{ secrets.CI_BOT_APP_PRIVATE_KEY }}
